_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/train.py
        e:
            njp5igaexty11pjb515mw2ndb0jj1cnt:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "3221225472"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494353338368"
                        used: "338681028608"
                email: bchharaw@uwaterloo.ca
                executable: /Users/brendanchharawala/Documents/GitHub/MSE446-Final-Project/venv/bin/python3
                git:
                    commit: e26c1c03fb25cbaac63bac58c57ba384ba78c680
                    remote: https://github.com/BChharaw/MSE446-Final-Project.git
                host: Brendans-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/brendanchharawala/Documents/GitHub/MSE446-Final-Project/train.py
                python: CPython 3.13.7
                root: /Users/brendanchharawala/Documents/GitHub/MSE446-Final-Project
                startedAt: "2025-11-25T02:21:41.212378Z"
                writerId: njp5igaexty11pjb515mw2ndb0jj1cnt
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.7
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
global:
    value:
        sample_rate: 16000
        stft:
            hop_length: 128
            n_fft: 512
paths:
    value:
        checkpoint_path: checkpoints/best.pth
        eval_output_dir: evaluation/results
        preprocess_vis_dir: visualizations/preprocess/spectrograms
        processed_train_dir: data_processed/train/audio
        processed_val_dir: data_processed/val/audio
        raw_noise_dir: data_raw/noise
        raw_speech_dir: data_raw/speech
train:
    value:
        batch_size: 8
        device: auto
        epochs: 5
        experiment_name: baseline
        learning_rate: 0.001
        seed: 0
        train_split: 0.9
